name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v10.1.0
        with:
          python-version: "3.12"
      - run: uv run --group dev pytest -v
      - run: sudo apt-get update && sudo apt-get install -y bubblewrap
      - run: bash tests/seccomp.sh
